name: NexEvent | DEV

on:
  push:
    branches: ['development']
  pull_request:
    branches: ['development']

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i -g pnpm
      - run: pnpm i

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Install PNPM - nexevent-api-dev
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE}}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            eval "$(ssh-agent -s)"
            ssh-add <(echo "$SSH_KEY")
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            cd /var/www/html/nexevent/api-dev
            ./step1.sh

      - name: Migration Run - nexevent-api-dev
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          passphrase: ${{ secrets.SSH_PASSPHRASE}}
          password: ${{ secrets.SSH_PASSWORD }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            eval "$(ssh-agent -s)"
            ssh-add <(echo "$SSH_KEY")
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            cd /var/www/html/nexevent/api-dev
            ./step2.sh

      - name: Deploy - nexevent-api-dev
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          passphrase: ${{ secrets.SSH_PASSPHRASE}}
          password: ${{ secrets.SSH_PASSWORD }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            eval "$(ssh-agent -s)"
            ssh-add <(echo "$SSH_KEY")
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            cd /var/www/html/nexevent/api-dev
            ./step3.sh
